# Generated by Django 4.0.5 on 2022-09-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_in',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height(in)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pcp',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Primary Care Provider'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pcp_address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Provider Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pcp_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Provider Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone'),
        ),
    ]
