# Generated by Django 4.0.5 on 2022-09-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0003_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_type',
            field=models.CharField(choices=[('O+', 'O Positive'), ('O-', 'O Negative'), ('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('UNK', 'Unknown')], max_length=10, verbose_name='Blood Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
