# Generated by Django 4.0.5 on 2022-09-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0005_allergyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=50, verbose_name='Medication Name')),
                ('med_indication', models.CharField(max_length=150, verbose_name='Clinical Indication')),
                ('med_dosage', models.CharField(max_length=50, verbose_name='Dosage')),
                ('med_frequency', models.CharField(max_length=50, verbose_name='Frequency')),
                ('med_start', models.CharField(blank=True, max_length=50, null=True, verbose_name='Start Date')),
                ('med_duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration')),
                ('med_ongoing', models.BooleanField(default=False, verbose_name='Currently Taking')),
            ],
        ),
        migrations.AlterField(
            model_name='allergyprofile',
            name='allergy_intervention',
            field=models.TextField(blank=True, null=True, verbose_name='Intervention/Treatment'),
        ),
        migrations.AlterField(
            model_name='allergyprofile',
            name='allergy_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
    ]
