# Generated by Django 4.0.5 on 2022-09-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0006_medicationprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_date', models.CharField(max_length=50, verbose_name='Date')),
                ('appt_time', models.CharField(max_length=50, verbose_name='Time')),
                ('appt_provider', models.CharField(max_length=50, verbose_name='Provider')),
                ('appt_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('appt_instructions', models.TextField(blank=True, null=True, verbose_name='Additional Instructions')),
            ],
        ),
    ]
