# Generated by Django 4.0.5 on 2022-09-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0007_appointmentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentprofile',
            name='appt_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
