# Generated by Django 4.0.5 on 2022-09-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0008_alter_appointmentprofile_appt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentprofile',
            name='appt_time',
            field=models.TimeField(verbose_name='Time'),
        ),
    ]
