# Generated by Django 4.0.5 on 2022-09-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0010_medicalhistoryprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100, verbose_name='Vaccine Name')),
                ('vaccine_date', models.DateField(verbose_name='Date Last Received')),
                ('vaccine_reaction', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Adverse Reactions')),
                ('vaccine_rxn_if_positive', models.TextField(blank=True, null=True, verbose_name='Describe reaction (Leave blank if no reaction)')),
                ('vaccine_next_due', models.DateField(blank=True, verbose_name='Next Due Date')),
                ('vaccine_notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
            ],
        ),
    ]
