# Generated by Django 4.0.5 on 2022-09-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0011_immunizationprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationprofile',
            name='vaccine_rxn_if_positive',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Describe reaction (Leave blank if none)'),
        ),
    ]
