# Generated by Django 4.0.5 on 2022-09-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0012_alter_immunizationprofile_vaccine_rxn_if_positive'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SN', 'Single'), ('MD', 'Married'), ('SP', 'Separated'), ('WD', 'Widowed')], max_length=3, verbose_name='Relationship Status')),
                ('smoker', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Smoker(Y/N)')),
                ('smoker_duration', models.CharField(blank=True, max_length=15, null=True, verbose_name='Duration')),
                ('smoker_frequency', models.CharField(blank=True, max_length=15, null=True, verbose_name='Frequency')),
                ('alcohol', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Alcohol(Y/N)')),
                ('alcohol_duration', models.CharField(blank=True, max_length=15, null=True, verbose_name='Duration')),
                ('alcohol_frequency', models.CharField(blank=True, max_length=15, null=True, verbose_name='Frequency')),
                ('drug', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Recreational Drugs(Y/N)')),
                ('drug_names', models.CharField(blank=True, max_length=15, null=True, verbose_name='Names')),
                ('drug_duration', models.CharField(blank=True, max_length=15, null=True, verbose_name='Duration')),
            ],
        ),
    ]
