# Generated by Django 4.0.5 on 2022-09-29 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0013_familysocialprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergyprofile',
            name='user_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.userprofile'),
        ),
    ]
