# Generated by Django 4.0.5 on 2022-09-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0015_appointmentprofile_user_instance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergyprofile',
            name='user_instance',
        ),
        migrations.RemoveField(
            model_name='appointmentprofile',
            name='user_instance',
        ),
        migrations.RemoveField(
            model_name='familysocialprofile',
            name='user_instance',
        ),
        migrations.RemoveField(
            model_name='immunizationprofile',
            name='user_instance',
        ),
        migrations.RemoveField(
            model_name='medicalhistoryprofile',
            name='user_instance',
        ),
        migrations.RemoveField(
            model_name='medicationprofile',
            name='user_instance',
        ),
        migrations.AddField(
            model_name='allergyprofile',
            name='user_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.userprofile'),
        ),
        migrations.AddField(
            model_name='appointmentprofile',
            name='user_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.userprofile'),
        ),
        migrations.AddField(
            model_name='familysocialprofile',
            name='user_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.userprofile'),
        ),
        migrations.AddField(
            model_name='immunizationprofile',
            name='user_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.userprofile'),
        ),
        migrations.AddField(
            model_name='medicalhistoryprofile',
            name='user_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.userprofile'),
        ),
        migrations.AddField(
            model_name='medicationprofile',
            name='user_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_records.userprofile'),
        ),
    ]
