# Generated by Django 4.0.5 on 2022-09-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0016_remove_allergyprofile_user_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationprofile',
            name='vaccine_next_due',
            field=models.DateField(blank=True, null=True, verbose_name='Next Due Date'),
        ),
    ]
